env:
  token: "ENCRYPTED[!414ff46c26e638f951714c8741af7b51f77812c4eb08d3076a0ed56607437bea241448e1b1657187d71cdd63f9214bee!]"

  chat_id: "ENCRYPTED[!655813cb6986b79acdf80606f20b48274840a8ff388e13c01fd1964ccfb0f6ec22304c635c1d473b00ce3f39939e6874!]"

  GH_TOKEN: "ENCRYPTED[!289e4d330898be91b3aeb2600ffc7d57346c85a5da0fa41132b5541c41c46fae0a50c1e132c744bd52695323c6dae5ee!]"

task:
  name: "Kernel deploy.."
  timeout_in: 120m
  container:
    image: accupara/aosp:baseline
    cpu: 8
    memory: 32G
    stateful: true
    greedy: true
  Build_script:
          
           git clone https://github.com/Shravan55555/scripts.git -b vayu --depth=1 &&
           chmod u+x scripts/sync.sh &&
           bash scripts/sync.sh
           #git clone https://github.com/Shravan55555/build_script.git && bash build_script/build.sh
          
           #bash <(curl -sL https://git.keyedlimepie.org/Shravan55555/Build_script.git)
          
           #rm -rf scripts && git clone https://github.com/Shravan55555/build_script.git && bash build_script/build.sh
